q2: q2.c
	gcc -lpthread q2.c -o q2

q3: q3.c
	gcc -lpthread q3.c -o q3

q4: q4.c
	gcc -lpthread q4.c -o q4

q5: q5.c
	gcc -lpthread q5.c -o q5

clean:
	for i in `ls`; do \
		[ -x $$i ] && rm $$i; \
	done
